/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class QuanLyDonHang extends javax.swing.JPanel {

    private final DefaultTableModel modelTable;  // Khai báo model bảng

    public QuanLyDonHang() {
        initComponents();
        // Khởi tạo model bảng với tên cột đúng
        modelTable = new DefaultTableModel(
            new Object[]{"Họ Tên", "Ngày Nhận", "Ngày Trả", "Dịch Vụ", "Trạng Thái"}, 0);
        tblthongtindonhang.setModel(modelTable);

        // Khởi tạo combo box với dữ liệu mẫu
        cbodichvu.removeAllItems();
        cbodichvu.addItem("Giặt ủi");
        cbodichvu.addItem("Sửa chữa");
        cbodichvu.addItem("Giao hàng");
        
        cbotrangthaidon.removeAllItems();
        cbotrangthaidon.addItem("Đang xử lý");
        cbotrangthaidon.addItem("Đã hoàn thành");
        cbotrangthaidon.addItem("Đã huỷ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btntaodon = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnxoadon = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btncapnhat = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtngaytra = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbotrangthaidon = new javax.swing.JComboBox<>();
        txthoten = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtngaynhan = new javax.swing.JTextField();
        cbodichvu = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblthongtindonhang = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Quản Lý Đơn Hàng");

        btntaodon.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btntaodon.setText("Tạo Đơn ");
        btntaodon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntaodonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Họ Tên");

        btnxoadon.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnxoadon.setText("Xoá Đơn ");
        btnxoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoadonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Ngày Nhận");

        btncapnhat.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btncapnhat.setText("Cập Nhật");
        btncapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncapnhatActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Ngày Trả");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Dịch Vụ");

        cbotrangthaidon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Trạng Thái Đơn");

        cbodichvu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Thông Tin Đơn Hàng");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtngaynhan))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(btncapnhat)
                                .addGap(70, 70, 70)
                                .addComponent(btnxoadon)
                                .addGap(87, 87, 87)
                                .addComponent(btntaodon)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(txtngaytra))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(cbodichvu, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addGap(33, 33, 33)
                                        .addComponent(cbotrangthaidon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txthoten))))))
                .addGap(269, 269, 269))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtngaytra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtngaynhan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbodichvu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cbotrangthaidon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnxoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncapnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntaodon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        tblthongtindonhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên Khách Hàng", "Ngày Nhận", "Ngày Trả", "Dịch Vụ"
            }
        ));
        jScrollPane2.setViewportView(tblthongtindonhang);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 935, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btntaodonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntaodonActionPerformed
   // Lấy dữ liệu từ các trường nhập liệu
String hoTen = txthoten.getText().trim();
String ngayNhan = txtngaynhan.getText().trim();
String ngayTra = txtngaytra.getText().trim();
String dichVu = cbodichvu.getSelectedItem().toString();
String trangThai = cbotrangthaidon.getSelectedItem().toString();

// Kiểm tra dữ liệu đầu vào (không được để trống)
if (hoTen.isEmpty() || ngayNhan.isEmpty() || ngayTra.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
    return;
}

// Kiểm tra định dạng ngày dd/MM/yyyy
SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
sdf.setLenient(false);

Date parsedNgayNhan = null;
Date parsedNgayTra = null;

try {
    parsedNgayNhan = sdf.parse(ngayNhan);
    parsedNgayTra = sdf.parse(ngayTra);

    // Kiểm tra ngày trả không được trước ngày nhận
    if (parsedNgayTra.before(parsedNgayNhan)) {
        JOptionPane.showMessageDialog(this, "Ngày trả phải lớn hơn hoặc bằng ngày nhận!");
        return;
    }
} catch (ParseException e) {
    JOptionPane.showMessageDialog(this, "Ngày nhận và ngày trả phải đúng định dạng dd/MM/yyyy!");
    return;
}

// In ra console để kiểm tra dữ liệu
System.out.println("Thông tin đơn hàng:");
System.out.println("Họ tên: " + hoTen);
System.out.println("Ngày nhận: " + ngayNhan);
System.out.println("Ngày trả: " + ngayTra);
System.out.println("Dịch vụ: " + dichVu);
System.out.println("Trạng thái: " + trangThai);

// TODO: Thêm dữ liệu đơn hàng vào bảng hoặc cơ sở dữ liệu
// Ví dụ nếu dùng JTable:
// modelTable.addRow(new Object[] {hoTen, ngayNhan, ngayTra, dichVu, trangThai});

// Hiển thị thông báo tạo đơn thành công
JOptionPane.showMessageDialog(this, "Đã tạo đơn hàng cho: " + hoTen);

// Xóa form (reset các trường nhập liệu)
clearForm();

    }//GEN-LAST:event_btntaodonActionPerformed

    private void btnxoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoadonActionPerformed
         int selectedRow = tblthongtindonhang.getSelectedRow();
    if (selectedRow >= 0) {
        modelTable.removeRow(selectedRow);
        JOptionPane.showMessageDialog(this, "Đã xoá đơn hàng.");
    } else {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn đơn hàng để xoá.");
    }
    }//GEN-LAST:event_btnxoadonActionPerformed

    private void btncapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncapnhatActionPerformed
        int selectedRow = tblthongtindonhang.getSelectedRow();
    if (selectedRow >= 0) {
        String hoTen = txthoten.getText();
        String ngayNhan = txtngaynhan.getText();
        String ngayTra = txtngaytra.getText();
        String dichVu = cbodichvu.getSelectedItem().toString();
        String trangThai = cbotrangthaidon.getSelectedItem().toString();

        if (hoTen.isEmpty() || ngayNhan.isEmpty() || ngayTra.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
            return;
        }

        modelTable.setValueAt(hoTen, selectedRow, 0);
        modelTable.setValueAt(ngayNhan, selectedRow, 1);
        modelTable.setValueAt(ngayTra, selectedRow, 2);
        modelTable.setValueAt(dichVu, selectedRow, 3);
        modelTable.setValueAt(trangThai, selectedRow, 4);

        JOptionPane.showMessageDialog(this, "Cập nhật đơn hàng thành công.");
        clearForm();
    } else {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn đơn hàng để cập nhật.");
    }
    }//GEN-LAST:event_btncapnhatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncapnhat;
    private javax.swing.JButton btntaodon;
    private javax.swing.JButton btnxoadon;
    private javax.swing.JComboBox<String> cbodichvu;
    private javax.swing.JComboBox<String> cbotrangthaidon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblthongtindonhang;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txtngaynhan;
    private javax.swing.JTextField txtngaytra;
    // End of variables declaration//GEN-END:variables

    private void clearForm() {
    txthoten.setText("");
    txtngaynhan.setText("");
    txtngaytra.setText("");
    cbodichvu.setSelectedIndex(0);
    cbotrangthaidon.setSelectedIndex(0);
    }
}
